# Generated by Django 4.2.6 on 2023-11-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitdata',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
